Use Lint/MissingSuper instead of Style/MethodMissingSuper
This commit fixes the following error:

> Error: The `Style/MethodMissingSuper` cop has been removed since
> it has been superseded by `Lint/MissingSuper`. Please use
> `Lint/MissingSuper` instead.

cf. https://github.com/rubocop-hq/rubocop/pull/8376